= Create an API Using the CLI
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: service mesh, microservices, downloading, installing

After you provision the adapter, you must create an API to bind to the service. You can create an API using Anypoint Platform or Anypoint Service Mesh:

* <<create-api-AP, Create an API using Anypoint Platform>>
+
Create APIs using Anypoint Platform when your API specification files are larger than 550 KB.
+
If you want to upload a REST API or an OAS asset type, use a `.json` or `.yaml` file. If you want to upload a SOAP API or WSDL asset type, use a `.wsdl` or `.xml` file.
* <<create-api-autocreate,Create an API using the Anypoint Service Mesh autocreate feature>>
+
You can configure Anypoint Service Mesh to automatically create an API in Anypoint Platform (no manual logging required). 
+
When creating APIs that require specification files, such as REST and SOAP APIs, ensure that the specification file is not larger than 550 KB and is available in your file system for the CLI to upload.
+
You can use any of the following options for authenticating the Anypoint Service Mesh autocreate feature:

** Using <<create-api-ASM-CLI, user credentials>>
+
Use the username and password authentication option if your users are managed by Anypoint Platform.  
** Using <<create-api-ASM-CLI-ConnAps, Connected Apps credentials>>
+
Use the xref:access-management::connected-apps-overview.adoc[Connected Apps] authentication option if your users are managed by an external identity provider (IdP).


[[create-api-AP]]
== Create an API Using Anypoint Platform

To create an API using Anypoint Platform, perform the following steps:

. Go to *Anypoint Platform > API Manager* and select the *Manage API* drop-down list. 
. Select *Create new API*.
+
The Creating an asset page is displayed.
. Specify a *Name* value and *Asset types* details for the API.  
+
Your asset is now created in Exchange for reuse. After you create the asset, you are ready to perform endpoint configuration.
+
The Endpoint Configuration window is displayed.
. In the *Managing type* field, select the *Basic Endpoint* radio button.
. In the *Application type* field, select the *Non-Mule application* radio button.
. Optionally, specify the *Implementation URI*, and click *Save*.
+
Your API is now created.

[[create-api-autocreate]]
== Create an API Using the Anypoint Service Mesh Autocreate Feature

When you configure the Anypoint Service Mesh autocreate feature, an API is automatically created for you. How you authenticate your user for the create transaction depends on whether your users are managed by Anypoint Platform or an external IdP.

[[create-api-ASM-CLI]]
=== Autocreate by Using Your User Credentials

If your users are managed by Anypoint Platform, use the username and password credentials for authentication. Before you configure the Anypoint Service Mesh autocreate feature, ensure that you obtain the:

* Environment ID and organization ID. 
+
To obtain these details, go to *API Manager > Environment Information*.
* Manage APIs Configuration permission for the environment where you are creating the API Instance.
* Exchange Contributor permission for the business group where you are creating the asset.

To autocreate using user credentials, perform the following steps:

. Using Anypoint Service Mesh, type the following command to create the API:
+
[source,text,linenums]
----
asmctl api create  
--name=_Kubernetes API resource name_ \
--namespace=_namespace name_ \
--environmentId=_environment ID_ \
--groupId=_(Optional) group ID of the asset, for example, organization ID_ \
--assetId=_asset ID on Exchange_ \
--version=_Asset version of the instance on exchange_ \
--instanceLabel=_label of the instance on API Manager_ \ 
--classifier=_(Optional) type of API specification, for example, oas_ \
--mainFile=_(Optional) name of the main file in the API specification_ \
--specPath=_(Optional) path to the API specification file_ \
--specTags=_list of comma separated tags to be added to the asset on Exchange_ \
--instanceTags=_list of comma separated tags to be added to the instance on API Manager_ \
--user=_username of the Anypoint Platform user, creating the API instance_ \
--password=_password of the Anypoint Platform user, creating the API instance_
----
+
[%header%autowidth.spread]
|===
| Parameter Name | Description | Required or Optional | Default Value
| `name` | The name of the Kubernetes API resource that you want to provision, for example, `orders-api` | Required | Not applicable
| `namespace` | The namespace in which you want to create the adapter, for example, `mulesoft-apps` | Optional | default
| `environmentId` | The ID of the environment where you want to create your API instance | Required | Not applicable
| `groupId` | The ID of the group of assets on Exchange, for example, the organization ID  | Optional | ID of the organization that contains the environment
| `assetId` | The ID, in alphanumeric characters without spaces, of the assets that are a part of an organization | Required | Not applicable
| `version` | The version of the asset on Exchange, including the semantic versioning format for major, minor, and patch releases  | Required | Not applicable
| `instanceLabel` | The ID, in alphanumeric characters without spaces, of the API instances of an asset within a given environment | Required | Not applicable
| `classifier` | The type of API asset to create: `http`, `oas`, or `raml`  | Optional | `http`
| `mainFile` | The name of the main file in the API specification file, compliant with the requirement that YAML or JSON files are named the same as the specification file, while the mainFile should match the primary file name when working with ZIP files | Specified for all classifiers except `http` | Not applicable
| `specPath` | The relative or absolute path to the API specification file | Required if classifier != `http` | Not applicable
| `specTags` | The tags to add to the asset on Exchange |  Optional | Not applicable
| `instanceTags` | The tags to add to the API instance on API Manager |  Optional | Not applicable
| `user` | The username credential of the Anypoint Platform user who creates the API | Required | Not applicable
| `password` | The password of the Anypoint Platform user who creates the API | Required | Not applicable
|===
+
. Verify the API status using the following command:
`asmctl api list`
+
The API that was created is displayed.
. Optionally, you can verify that an asset is created on Exchange and an API is created on API Manager.

[[create-api-ASM-CLI-ConnAps]]
=== Autocreate by Using Your Connected Apps Credentials

If your users are managed by Anypoint Platform or an external IdP, use the Connected App credentials for authentication. Before you configure the autocreate feature, ensure that:

* You xref:obtain-connected-apps-credentials.adoc[Obtain the client ID and client secret credentials] from Connected Apps
* The ID of the group of assets on Exchange, for example, the organization ID
* The client credentials has the:
** Exchange Contributor permission for publishing the API to Exchange
** Manage API Configuration permission for managing the API in API Manager

To autocreate using Connected Apps, perform the following steps:

. Using Anypoint Service Mesh, type the following command to create the API:
+
[source,text,linenums]
----
asmctl api create
--name=_Kubernetes API resource name_ \
--namespace=_namespace name_ \
--environmentId=_environment ID_ \
--groupId=_(Optional) group ID of the asset, for example, organization ID_ \
--assetId=_asset ID on Exchange_ \
--version=_asset version of the instance on exchange_ \
--instanceLabel=_label of the instance on API Manager_ \
--specTags=_list of comma separated tags to be added to the asset on Exchange_ \
--instanceTags=_list of comma separated tags to be added to the instance on API Manager_ \
--clientId=_ID of the Anypoint Platform Connected Apps, using which to create the API instance_ \
--clientSecret=_client secret of the Anypoint Platform Connected Apps, using which to create the API instance_
----
+
[%header%autowidth.spread]
|===
| Parameter Name | Description | Required or Optional | Default Value
| `name` | The name of the Kubernetes API resource that you want to provision, for example, `orders-api` | Required | Not applicable
| `namespace` | The namespace in which you want to create the adapter, for example, `mulesoft-apps` | Optional | default
| `environmentId` | The ID of the environment where you want to create your API instance | Required | Not applicable
| `groupId` | The ID of the group of assets on Exchange, for example, the organization ID, which you can obtain from the API Manager landing page or in Access Management | Optional | Organization ID of the organization that contains the environment. 
| `assetId` | The ID of the assets that are a part of an organization, in alphanumeric characters without spaces | Required | Not applicable
| `version` | The version of the asset on Exchange, in the semantic versioning format for major, minor, and patch releases | Required | Not applicable
| `instanceLabel` | The ID of the API instances of an asset within a given environment, in alphanumeric characters without spaces | Required | Not applicable
| `specTags` | Tags to add to the asset on Exchange |  Optional | Not applicable
| `instanceTags` | Tags to add to the API instance on API Manager |  Optional | Not applicable
| `clientId` | The client ID of the Anypoint Platform Connected App used to create the API | Required | Not applicable
| `clientSecret` | The client secret of the Anypoint Platform Connected App used to create the API | Required | Not applicable
|===
+
. Verify the API status:
`asmctl api list`
+
The new API is displayed.
. Optionally, verify that an Exchange asset is created on Exchange and an API is created on API Manager.

== See Also

* xref::bind-api-configure-service-mesh-CLI.adoc[Bind a Service Using CLI]
* xref::manage-apis-with-service-mesh.adoc[Manage APIs with Anypoint Service Mesh]
* xref::uninstall-service-mesh.adoc[Uninstall Anypoint Service Mesh]
* xref:exchange::ex2-to-simulate-api-data.adoc[Simulate Data in REST APIs]
