= Create an API Using the CLI
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: service mesh, microservices, downloading, installing

After you provision the adapter, you must create an API to bind to the service. You can create an API using Anypoint Platform or Anypoint Service Mesh:

* <<create-api-ASM-CLI, Create an API using Anypoint Service Mesh Autocreate>>
+
Anypoint Service Mesh enables you to automatically create an API in Anypoint Platform. You do not have to manually log in to Anypoint Platform. 
+
When creating APIs that require specification files, such as REST and SOAP, ensure that the specification file is available in your file system for the CLI to upload it. Specification files used in this provisioning approach must not exceed 550 KBs in size.
* <<create-api-AP, Create an API using Anypoint Platform>>
+
You can manually create APIs using Anypoint Platform. Use this approach for API specification files that are greater than 550 KBs.

+
If you want to upload a REST API or OAS asset type, use a .json or .yaml file. Alternatively, if you want to upload a SOAP API or WSDL asset type, use a .wsdl or .xml file.

[[create-api-AP]]
== Create an API Using Anypoint Platform

To create an API using Anypoint Platform, perform the following steps:

. Go to *Anypoint Platform > API Manager* and select the *Manage API* drop-down list. 
. Select *Create new API*.
+
The Creating an asset page is displayed.
. Specify a *Name* value and *Asset types* details for the API.  
+
Your asset is now created in Exchange for reuse. After you create the asset, you are ready to perform endpoint configuration.
+
The Endpoint Configuration window is displayed.
. In the *Managing type* field, select the *Basic Endpoint* radio button.
. In the *Application type* field, select the *Non-Mule application* radio button.
. Optionally, specify the *Implementation URI*, and click *Save*.
+
Your API is now created.

[[create-api-ASM-CLI]]
== Create an API Using Anypoint Service Mesh

Use the procedure in this section to automatically create an API using Anypoint Service Mesh. Before you create the API, you must complete the task prerequisite.

*Task Prerequisite*

Before you begin, ensure that you obtain the:

* Environment ID and organization ID. 
+
To obtain these details, go to *API Manager > Environment Information*.
* Manage APIs Configuration permission for the environment where you are creating the API Instance.
* Exchange Contributor permission for the business group where you are creating the asset.

To create an API using Anypoint Service Mesh, perform the following steps:

. Using Anypoint Service Mesh, type the following command to create the API:
+
[source,text,linenums]
----
asmctl api create  
--name=_Kubernetes API resource name_ \
--namespace=_namespace name_ \
--environmentId=_environment ID_ \
--groupId=_(Optional) group ID of the asset, for example, organization ID_ \
--assetId=_asset ID on Exchange_ \
--version=_Asset version of the instance on exchange_ \
--instanceLabel=_label of the instance on API Manager_ \ 
--classifier=_(Optional) type of API specification, for example, oas_ \
--mainFile=_(Optional) name of the main file in the API specification_ \
--specPath=_(Optional) path to the API specification file_ \
--specTags=_list of comma separated tags to be added to the asset on Exchange_ \
--instanceTags=_list of comma separated tags to be added to the instance on API Manager_ \
--user=_username of the Anypoint Platform user, creating the API instance_ \
--password=_password of the Anypoint Platform user, creating the API instance_
----
+
[%header%autowidth.spread]
|===
| Parameter Name | Description | Required or Optional | Default Value
| `name` | The name of the Kubernetes API resource that you want to provision, for example, `orders-api`. | Required | Not applicable
| `namespace` | The namespace in which you want to create the adapter, for example, `mulesoft-apps`. | Optional | default
| `environmentId` | The ID of the environment where you want to create your API instance. | Required | Not applicable
| `groupId` | The ID of the group of assets on Exchange, for example, the organization ID. You can find the organization ID on the API Manager landing page or in Access Management. | Optional | Organization ID of the organization that contains the environment. 
| `assetId` | The ID of the assets that are a part of an organization. Supports alphanumeric characters without spaces. | Required | Not applicable
| `version` | The version of the asset on Exchange. The version number must follow the semantic versioning format for major, minor, and patch releases. | Required | Not applicable
| `instanceLabel` | The ID of the API instances of an Asset within a given environment. Supports alphanumeric characters without spaces. | Required | Not applicable
| `classifier` | The asset kind of the API to create. Available options include `http`, `oas`, `raml`.  | Optional | `http`
| `mainFile` | The name of the main file in the API specification file. When uploading a single YAML or JSON file, it should be the same name as the file. When uploading a ZIP file, it must match the primary file. | Required if classifier != `http` | Not applicable
| `specPath` | The relative or absolute path to the API specification file. | Required if classifier != `http` | Not applicable
| `specTags` | Tags to add to the asset on Exchange. |  Optional | Not applicable
| `instanceTags` | Tags to add to the API instance on API Manager. |  Optional | Not applicable
| `user` | The username credential of the Anypoint Platform user who is creating the API. | Required | Not applicable
| `password` | The password of the Anypoint Platform user who is creating the API. | Required | Not applicable
|===
+
. Verify the API status using the following command:
`asmctl api list`
+
The API that was created is displayed.
. Optionally, you can verify that an asset is created on Exchange and an API is created on API Manager.

== See Also

* xref::bind-api-configure-service-mesh-CLI.adoc[Bind a Service Using CLI]
* xref::manage-apis-with-service-mesh.adoc[Manage APIs with Anypoint Service Mesh]
* xref::uninstall-service-mesh.adoc[Uninstall Anypoint Service Mesh]
* xref:exchange::ex2-to-simulate-api-data.adoc[Simulate Data in REST APIs]
