= Troubleshoot Service Binding Issues
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: service mesh, microservices, service binding issues, troubleshooting

After you create the API, you then bind your service with the API. This section provides possible causes for issues that might occue when you bind your service, and describes how to troubleshoot these errors:

* <<dns-name-error,Binding name is not in DNS subdomain standard format>>
* <<references-non-existent-instance-error,References non-existent instance error>>

[[dns-name-error]]
== Name is not DNS subdomain standard format

If you provide a DNS name that does not comply with the DNS subdomain standard format, an error occurs and the binding fails.

=== Diagnose

The output of the binding creation command displays that binding failed. 

`The ServiceBinding "customer-API" is invalid: metadata.name: Invalid value: "customer-API": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

=== Solution

Ensure that you provide binding name value that follow the DNS subdomain standards.


[[references-non-existent-instance-error]]
== References Non-existent Instance Error

When you create a binding, you must reference an API or an adapter previously by referencing its name. Otherwise, you receive this error message.

== Causes

This error can occur if:
 
* The adapter name in the binding command is incorrect (adapter binding).
* The API name in the binding command is incorrect (API binding).
* The Namespace flag was not provided and therefore the service was searched for in the `default` namespace.


=== Diagnose

Diagnose this issue by running one of the following commands:

* `$ asmctl api binding list`
* `$ asmctl adapter binding list`
+
The status of binding displays as `ReferencesNonexistentInstance`.

=== Solution

Delete the erroneous binding command and re-create it with the correct input.

