= Troubleshooting Service Binding Issues
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: service mesh, microservices, service binding issues, troubleshooting

After you create the API, you then bind your service with the API. This section provides possible causes for issues that might occue when you bind your service, and describes how to troubleshoot these errors:

* <<dns-name-error,DNS Name Error>>
* <<references non-existent-instance-error,References non-existent instance error>>
* <<missing-entitlements-in-license,Missing entitlements in license>>

[[dns-name-error]]
== DNS Name Error

If you provide a DNS name that does not comply with the DNS subdomain standard format, an error occurs and the binding fails.

=== Cause

This issue occurs if you provided a DNS name that does not follow the DNS subdomain standards.

=== Diagnose

To diagnose this issue, run one of the following commands:
+
`$ ./service-mesh api binding list` Or `$ ./service-mesh adapter binding list`.
+
The output of this command displays a Failed status of the binding:
+
`The ServiceBinding "customer-API" is invalid: metadata.name: Invalid value: "customer-API": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`.

=== Solution

Ensure that you provide DNS name values that follow the DNS subdomain standards.

[[references non-existent-instance-error]]
== References Non-existent Instance Error

When creating a binding, the binding command requires you to provide a name for the service and the name of the adapter that you created previously. Errors can occur if you did not specify the correct parameters for the binding command.

== Causes

This error occur can occur due to multiple reasons:
 
* Service does not  exist because:
* Incorrect service name specified when referring to the service name.
* The Namespace flag was not provided and therefore the service was searched for in the `default` namespace.
* The adapter does not exist because an incorrect adapter name was specified when referring to the adapter name.


=== Diagnose

To diagnose this issue, run one of the following commands:
+
`$ ./service-mesh api binding list`
Or
`$ ./service-mesh adapter binding list`
+
The status of binding displays the `ReferencesNonexistentInstance` status.

=== Solution

Delete the erroneous binding and recreate it with the correct input.

[[missing-entitlements-in-license]]
== Missing Entitlements in License

To successfully install and use Anypoint Service Mesh, you must have applied a valid license with correct entitlements.

=== Causes

If the license you applied when installing Anypoint Service Mesh does not have the correct entitlements, you encounter errors.


=== Diagnose

To diagnose this issue:

. Check the adapter status:
+
`$ ./service-mesh adapter list`
. If the adapter status is Failed, review the adapter logs:
+
`$ ./service-mesh api binding logs --namespace=<replace_with_namespace> --name=<replace_with_adapter_name>`
+
The command displays an output like this:
+`
DATE                   MESSAGE
2019-11-26T18:15:00Z   The binding is being created asynchronously
2019-11-26T18:16:52Z   The binding is being created asynchronously (wait all endpoints health check)
2019-11-26T18:17:12Z   Bind call failed: endpoints health check failed`
. Obtain the adapter logs and verify the license entitlements:
+
`$ kubectl -n service-mesh logs $(kubectl -n service-mesh get pod -l namespace=<replace_with_namespace> -oname) -c mule | grep license`.
+
The output must display valid licenses and must have at least the api-gateway and clustering entitlements:
+
`Valid license key --> Evaluation = false, Expiration Date = Thu Dec 30 23:00:00 GMT 2100, Contact Name = Mule, Contact Email Address = support@mulesoft.com, Contact Telephone = 00000, Contact Company = MuleSoft, Contact Country = US, Entitlements = clustering,api-gateway`

=== Solution

To resolve this error:

. Replace the licence with a valid one:
+
`$ kubectl create secret generic -n service-mesh --dry-run service-mesh-incluster-broker-impl-license --from-file=license=<license_path> -oyaml | kubectl apply -n service-mesh -f -`.
. Redeploy the adapter:
+
`$ kubectl -n service-mesh patch $(kubectl -n service-mesh get deploy -l namespace=<replace_with_namespace> -oname) --type=json -p="[{\"op\": \"replace\", \"path\": \"/spec/template/metadata/annotations/kubectl.kubernetes.io~1restartedAt\",\"value\":\"$(date -u +%FT%TZ)\"}]"`.
. Remove the failed bindings and recreate them:
+ 
`$ ./service-mesh api binding delete --namespace=<replace_with_namespace> --name=<replace_with_adapter_name>`.



