= Troubleshooting API Provisioning Issues
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: service mesh, microservices, API provisioning issues, troubleshooting

After you provision an adapter, you must create an API, to which you then bind the service. You might encounter errors when you provision an API if you provide invalid credentials, and so on. 

//Should I move this error to the Service errors topic and call the topic "API and Service Issues"?

== Error With Parameters

When you create an API, you must provide valid username and password credentials.

=== Cause

If you provide incorrect credentials, the following error occurs:
//need text of the screenshot here

=== Diagnosis

To diagnose the issue:

. Describe your service instance:
+
`$ kubectl describe serviceinstance inventory-resource-api`.
In the `Status` field, a detailed description of the error is displayed:
//Need text of the screenshot here.

In the following example, an error occurred due to an extra comma in the stringData section that is provided after the password segment:

[source,text,linenums]
----
apiVersion: v1
kind: Secret
metadata:
  name: my-credentials
  namespace: nto-payment
type: Opaque
stringData:
  user-pass:
    '{
      "user": "<user>",
      "password": "<password>",
    }'
----

=== Solution

To resolve this issue:

. Delete the API.
. Resolve the error with the username and password credentials.
. Recreate the API.  
