= Upgrade to Anypoint Service Mesh 1.2
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: service mesh, microservices, upgrading


Anypoint Service Mesh v1.2 introduces support for Red Hat OpenShift. Note that implementing these changes might require some downtime.


== Prerequisites

Before you upgrade, ensure that your environment uses:

* Anypoint Service Mesh v1.1.x
* The most recent version of the Anypoint Service Mesh command line interface (CLI)
+
The CLI version must be v1.2.x and the Anypoint Service Mesh version must be v1.1.x.
* Should count with Kubernetes and Istio xref:prepare-to-install-service-mesh.adoc#supported_versions[versions supported by 1.2.x].


== Steps

To upgrade to Anypoint Service Mesh v1.2:

. If you have not already done so, download the latest Anypoint Service Mesh command line interface (CLI) version:
+
`curl -Ls http://anypoint.mulesoft.com/servicemesh/xapi/v1/install > asmctl && chmod +x asmctl`
. Upgrade Anypoint service Mesh
+
`$ asmctl upgrade`
+
[NOTE] If you are using the EU control plane, you must specify the correct `--platformUri` flag for the upgrade.






