= Anypoint Service Mesh
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: service mesh, microservices, cluster, container

Anypoint Service Mesh enables accelerated adoption of microservices by providing discoverability, management, and security for non-MuleSoft microservices. These non-MuleSoft microservices might be written using different languages and platforms, or might be deployed in different environments.

To alleviate issues arising from differences in these microservices, Anypoint Service Mesh ensures the following application management advantages:
Provides resilient service-to-service communication using zero-trust policies to handle traffic control, fault tolerance and load balancing 
Extends MuleSoft API Management capabilities to any non-Mule service, with policies, security and analytics all applied directly from Anypoint Platform
Amplifies reuse of services with discovery of non-Mule services within Exchange, available for use in future projects


== Business Solution

Growing business demands for diverse deployment environments also introduces a need for rapidly deployable and manageable microservices architecture. In a microservice architecture, you build smaller, targeted services instead of large monolithic applications. These services are faster to build, easier to maintain, and help foster agility. 

In a common enterprise setup, there are numerous teams building services that connect and expose functionalities across all sorts of systems: mainframes, SaaS apps, IoT devices, and so on. The result is usually a siloed environment, with teams managing these apps in different ways. 

With Anypoint Service Mesh from MuleSoft you can connect your applications, data, and devices through APIs in an applications network. You can manage, govern and secure your application network within Anypoint Platform.

Microservices might exist outside of the MuleSoft ecosystem, all built in different languages and deployed to different environments. Anypoint Service Mesh enables you to extend your application network to any type of microservice. 

Most importantly, the Anypoint Service Mesh can perform these tasks across all services, independent of the technology upon which it is built. Developers can focus on building out the business logic within. You can now discover, manage and secure any type of microservice from a central control plane in the Anypoint Platform.



== Anypoint Service Mesh Architecture
A service mesh is an independent architecture layer, which is encapsulated in a Kubernetes cluster. In a service mesh architecture, instead of the services communicating with one another, a sidecar proxy is used to perform the same job. The manner in which these sidecars interact is governed by an overall mixer, where a user can apply different policies and security.

As illustrated in the diagram, at the top of the architecture is Anypoint Platform, which brings complete lifecycle API management capabilities to the microservices built with Mule Runtime engine. These Mule Runtimes might be deployed within CloudHub, or a Runtime Fabric at your location. 


== See Also

*** xref:viewing-api-analytics.adoc[Reviewing Analytics usage]
*** xref:analytics-chart.adoc[Reviewing API Manager Analytics charts usage]
*** xref:analytics-event-api.adoc[Reviewing Analytics Event API]
*** xref:analytics-event-forward.adoc[Reviewing Analytics Event Forwarding]